#include "SLMouseActor.h"
#include "Character/BattleComponent/BattleComponent.h"
#include "Character/SLPlayerCharacter.h"
#include "Components/StaticMeshComponent.h"
#include "Components/SphereComponent.h"
#include "NiagaraFunctionLibrary.h"
#include "Kismet/GameplayStatics.h"
#include "Kismet/KismetMathLibrary.h"
#include "Engine/World.h"
#include "TimerManager.h"
#include "GameFramework/CharacterMovementComponent.h"

ASLMouseActor::ASLMouseActor()
{
	PrimaryActorTick.bCanEverTick = true;

	// ì»´í¬ë„ŒíŠ¸ ìƒì„±
	RootSceneComponent = CreateDefaultSubobject<USceneComponent>(TEXT("RootSceneComponent"));
	RootComponent = RootSceneComponent;

	MouseMeshComponent = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("MouseMeshComponent"));
	MouseMeshComponent->SetupAttachment(RootComponent);
	MouseMeshComponent->SetCollisionResponseToChannel(ECC_Pawn, ECR_Overlap);

	CollisionComponent = CreateDefaultSubobject<USphereComponent>(TEXT("CollisionComponent"));
	CollisionComponent->SetupAttachment(RootComponent);
	CollisionComponent->SetCollisionResponseToChannel(ECC_Pawn, ECR_Block);
	CollisionComponent->SetCollisionResponseToChannel(ECC_GameTraceChannel1, ECR_Block);

	BattleComponent = CreateDefaultSubobject<UBattleComponent>(TEXT("BattleComponent"));

	// Orbit Settings ì´ˆê¸°í™”
	OrbitRadius = 300.0f;
	OrbitHeight = 400.0f;
	OrbitSpeed = 90.0f;
	MoveToOrbitSpeed = 500.0f;

	// Movement Settings ì´ˆê¸°í™”
	DescentSpeed = 800.0f;
	GrabMoveSpeed = 600.0f;

	// Grab Settings ì´ˆê¸°í™”
	GrabDistance = 500.0f;
	GrabHeight = 300.0f;
	GrabDamage = 20.0f;
	GrabCooldownMin = 2.0f;
	GrabCooldownMax = 5.0f;
	CollisionDisableTime = 2.0f;

	// General Settings ì´ˆê¸°í™”
	MaxHealth = 100.0f;
	DetectionRange = 100.0f;

	// Effects ì´ˆê¸°í™”
	GrabEffect = nullptr;
	DestroyEffect = nullptr;
	GrabSound = nullptr;
	DestroySound = nullptr;

	// Phase 3 Settings ì´ˆê¸°í™”
	Phase3ChaseSpeed = 800.0f;
	Phase3StopDistance = 100.0f;
	PlayerLookCheckAngle = 15.0f;
	Phase3HorrorMesh = nullptr;
	Phase3HorrorScale = FVector(1.0f, 1.0f, 1.0f);
	SweepAttackDamage = 30.0f;
	SweepAttackRange = 500.0f;
	SweepAttackCooldown = 5.0f;
	SweepAttackEffect = nullptr;
	bShowSweepDebug = true;
	SweepAttackHitCount = 5;
	SweepAttackHitInterval = 0.1f;

	// Phase 5 Settings ì´ˆê¸°í™”
	DefaultWallStunDuration = 3.0f;
	StunEffect = nullptr;
	StunSound = nullptr;

	// Private Variables ì´ˆê¸°í™”
	CurrentState = EMouseActorState::Inactive;
	CurrentHealth = 0.0f;
	TargetPlayer = nullptr;
	GrabTargetLocation = FVector::ZeroVector;
	MoveToOrbitTargetLocation = FVector::ZeroVector;
	bCanGrab = true;
	OrbitAngle = 0.0f;
	OrbitCenter = FVector::ZeroVector;

	bIsInPhase3Mode = false;
	bIsPlayerLookingAtMe = false;
	OriginalMesh = nullptr;

	bCanSweepAttack = true;
	CurrentHitCount = 0;

	bIsStunned = false;
	bIsAttackable = false;
}

void ASLMouseActor::BeginPlay()
{
    Super::BeginPlay();

    // ë©”ì‹œ ì»´í¬ë„ŒíŠ¸ ì½œë¦¬ì „ ì„¤ì • - ê³µê²© ë°›ì„ ìˆ˜ ìˆë„ë¡ ìˆ˜ì •
    if (MouseMeshComponent)
    {
        MouseMeshComponent->SetCollisionEnabled(ECollisionEnabled::QueryAndPhysics);
        MouseMeshComponent->SetCollisionObjectType(ECC_WorldDynamic);
        MouseMeshComponent->SetCollisionResponseToAllChannels(ECR_Block);
        MouseMeshComponent->SetCollisionResponseToChannel(ECC_Camera, ECR_Ignore);
        MouseMeshComponent->SetCollisionResponseToChannel(ECC_GameTraceChannel1, ECR_Block); // ê³µê²© ì±„ë„
    }

    // ì½œë¦¬ì „ ì»´í¬ë„ŒíŠ¸ ì„¤ì •
    if (CollisionComponent)
    {
        CollisionComponent->OnComponentHit.AddDynamic(this, &ASLMouseActor::OnCollisionHit);
        CollisionComponent->SetSphereRadius(DetectionRange);
        
        // ê¸°ë³¸ ì½œë¦¬ì „ ì„¤ì • - ê³µê²© ë°›ì„ ìˆ˜ ìˆë„ë¡
        CollisionComponent->SetCollisionEnabled(ECollisionEnabled::QueryAndPhysics);
        CollisionComponent->SetCollisionObjectType(ECC_WorldDynamic);
        CollisionComponent->SetCollisionResponseToAllChannels(ECR_Block);
        CollisionComponent->SetCollisionResponseToChannel(ECC_Camera, ECR_Ignore);
        CollisionComponent->SetCollisionResponseToChannel(ECC_Pawn, ECR_Overlap);
        CollisionComponent->SetCollisionResponseToChannel(ECC_GameTraceChannel1, ECR_Block); // ê³µê²© ì±„ë„
    }

    if (BattleComponent)
    {
        BattleComponent->OnCharacterHited.AddDynamic(this, &ASLMouseActor::OnBattleComponentHit);
        // BattleComponent ê¸°ë³¸ í™œì„±í™”
        BattleComponent->SetComponentTickEnabled(true);
    }

    TargetPlayer = FindPlayerCharacter();
    CurrentHealth = MaxHealth;
    bCanGrab = true;
    OrbitAngle = 0.0f;
    
    // Phase5ê°€ ì•„ë‹Œ ê²½ìš° ê¸°ë³¸ì ìœ¼ë¡œ ê³µê²© ë¶ˆê°€ëŠ¥
    bIsAttackable = false;
}

void ASLMouseActor::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);

	if (CurrentState == EMouseActorState::Destroyed)
	{
		return;
	}

	if (!IsValid(TargetPlayer))
	{
		TargetPlayer = FindPlayerCharacter();
		if (!IsValid(TargetPlayer))
		{
			return;
		}
	}

	if (bIsStunned)
	{
		UpdateMeshRotation(DeltaTime); // íšŒì „ë§Œ ìœ ì§€
		return;
	}
	
	if (bIsInPhase3Mode)
	{
		UpdatePhase3Movement(DeltaTime);
		UpdateMeshRotation(DeltaTime);
		return;
	}

	switch (CurrentState)
	{
	case EMouseActorState::MovingToOrbit:
		UpdateMoveToOrbitMovement(DeltaTime);
		break;
        
	case EMouseActorState::Orbiting:
		UpdateOrbitMovement(DeltaTime);
		if (CanGrabPlayer())
		{
			SetMouseActorState(EMouseActorState::Descending);
		}
		break;
        
	case EMouseActorState::Descending:
		UpdateDescentMovement(DeltaTime);
		if (IsPlayerInRange())
		{
			StartGrabPlayer();
		}
		break;
        
	case EMouseActorState::Grabbing:
		UpdateGrabMovement(DeltaTime);
		break;
	}

	UpdateMeshRotation(DeltaTime);
}

void ASLMouseActor::StartOrbiting()
{
	if (CurrentState == EMouseActorState::Destroyed)
	{
		return;
	}

	TargetPlayer = FindPlayerCharacter();
	
	if (!IsValid(TargetPlayer))
	{
		UE_LOG(LogTemp, Warning, TEXT("Mouse Actor: No valid player found for orbiting"));
		return;
	}

	OrbitCenter = TargetPlayer->GetActorLocation();
	OrbitAngle = 0.0f;
	
	MoveToOrbitTargetLocation = CalculateOrbitPosition();
	
	SetMouseActorState(EMouseActorState::MovingToOrbit);
}

void ASLMouseActor::StopOrbiting()
{
	if (CurrentState == EMouseActorState::Grabbing && IsValid(TargetPlayer))
	{
		TargetPlayer->DetachFromActor(FDetachmentTransformRules::KeepWorldTransform);
		TargetPlayer->CharacterDragged(false);
		
		if (UCharacterMovementComponent* MovementComp = TargetPlayer->GetCharacterMovement())
		{
			MovementComp->SetDefaultMovementMode();
		}
	}

	SetMouseActorState(EMouseActorState::Inactive);
	
	if (IsValid(CollisionComponent))
	{
		CollisionComponent->SetCollisionEnabled(ECollisionEnabled::QueryAndPhysics);
	}
}

void ASLMouseActor::DestroyMouseActor()
{
	if (CurrentState == EMouseActorState::Destroyed)
	{
		return;
	}

	if (CurrentState == EMouseActorState::Grabbing && IsValid(TargetPlayer))
	{
		TargetPlayer->DetachFromActor(FDetachmentTransformRules::KeepWorldTransform);
		TargetPlayer->CharacterDragged(false);
		
		if (UCharacterMovementComponent* MovementComp = TargetPlayer->GetCharacterMovement())
		{
			MovementComp->SetDefaultMovementMode();
		}
	}

	SetMouseActorState(EMouseActorState::Destroyed);

	if (IsValid(DestroyEffect) && IsValid(GetWorld()))
	{
		UNiagaraFunctionLibrary::SpawnSystemAtLocation(
			GetWorld(),
			DestroyEffect,
			GetActorLocation(),
			GetActorRotation()
		);
	}

	if (IsValid(DestroySound) && IsValid(GetWorld()))
	{
		UGameplayStatics::PlaySoundAtLocation(
			GetWorld(),
			DestroySound,
			GetActorLocation()
		);
	}

	if (OnMouseActorDestroyed.IsBound())
	{
		OnMouseActorDestroyed.Broadcast(this);
	}

	SetActorHiddenInGame(true);
	SetActorEnableCollision(false);
	SetActorTickEnabled(false);

}

EMouseActorState ASLMouseActor::GetCurrentState() const
{
	return CurrentState;
}

void ASLMouseActor::OnCollisionHit(UPrimitiveComponent* HitComponent, AActor* OtherActor, UPrimitiveComponent* OtherComponent, FVector NormalImpulse, const FHitResult& Hit)
{
	if (!IsValid(OtherActor) || CurrentState == EMouseActorState::Destroyed)
	{
		return;
	}

	if (ASLPlayerCharacter* PlayerCharacter = Cast<ASLPlayerCharacter>(OtherActor))
	{
		if (IsValid(PlayerCharacter) && CurrentState == EMouseActorState::Descending && CanGrabPlayer())
		{
			StartGrabPlayer();
		}
	}
}

void ASLMouseActor::OnBattleComponentHit(AActor* DamageCauser, float DamageAmount, const FHitResult& HitResult, EHitAnimType HitAnimType)
{
    UE_LOG(LogTemp, Warning, TEXT("ğŸ¯ OnBattleComponentHit called!"));
    UE_LOG(LogTemp, Warning, TEXT("   DamageCauser: %s"), DamageCauser ? *DamageCauser->GetName() : TEXT("NULL"));
    
    if (DamageCauser)
    {
        UE_LOG(LogTemp, Warning, TEXT("   DamageCauser Class: %s"), *DamageCauser->GetClass()->GetName());
    }
    
    UE_LOG(LogTemp, Warning, TEXT("   DamageAmount: %f"), DamageAmount);
    UE_LOG(LogTemp, Warning, TEXT("   HitAnimType: %d"), static_cast<int32>(HitAnimType));
    UE_LOG(LogTemp, Warning, TEXT("   Hit Location: %s"), *HitResult.ImpactPoint.ToString());
    UE_LOG(LogTemp, Warning, TEXT("   Current State: %d"), static_cast<int32>(CurrentState));
    UE_LOG(LogTemp, Warning, TEXT("   bIsAttackable: %s"), bIsAttackable ? TEXT("YES") : TEXT("NO"));
    UE_LOG(LogTemp, Warning, TEXT("   bIsStunned: %s"), bIsStunned ? TEXT("YES") : TEXT("NO"));

    if (CurrentState == EMouseActorState::Destroyed)
    {
        UE_LOG(LogTemp, Warning, TEXT("âŒ Mouse Actor already destroyed - ignoring damage"));
        return;
    }
    
    // ê³µê²© ê°€ëŠ¥í•œ ìƒíƒœê°€ ì•„ë‹ˆë©´ ë°ë¯¸ì§€ ë¬´ì‹œ
    if (!bIsAttackable)
    {
        UE_LOG(LogTemp, Warning, TEXT("âŒ Mouse Actor is not attackable - damage ignored"));
        UE_LOG(LogTemp, Warning, TEXT("   Try calling ApplyWallStun() first or ForceEnableAttack() for testing"));
        return;
    }

    UE_LOG(LogTemp, Warning, TEXT("âœ… Damage accepted! Applying %f damage"), DamageAmount);

    CurrentHealth -= DamageAmount;
    
    UE_LOG(LogTemp, Warning, TEXT("ğŸ¯ Mouse Actor hit! Remaining Health: %f / %f"), CurrentHealth, MaxHealth);

    // ë°ë¯¸ì§€ ì´í™íŠ¸ë‚˜ ì‚¬ìš´ë“œ ì¬ìƒ (ì„ íƒì )
    if (IsValid(GrabEffect) && IsValid(GetWorld()))
    {
        UNiagaraFunctionLibrary::SpawnSystemAtLocation(
            GetWorld(),
            GrabEffect,
            GetActorLocation(),
            GetActorRotation()
        );
    }

    if (CurrentHealth <= 0.0f)
    {
        UE_LOG(LogTemp, Warning, TEXT("ğŸ’€ Mouse Actor health depleted - destroying"));
        DestroyMouseActor();
    }
}

void ASLMouseActor::OnGrabCooldownFinished()
{
	bCanGrab = true;
	OnMouseGrabCooldownFinished.Broadcast();
}

void ASLMouseActor::OnCollisionReenabled()
{
	if (IsValid(CollisionComponent))
	{
		if (bIsInPhase3Mode)
		{
			// Phase3ì—ì„œëŠ” ê²¹ì¹¨ë§Œ í—ˆìš©
			CollisionComponent->SetCollisionEnabled(ECollisionEnabled::QueryOnly);
			CollisionComponent->SetCollisionResponseToAllChannels(ECR_Ignore);
			CollisionComponent->SetCollisionResponseToChannel(ECC_Pawn, ECR_Overlap);
			CollisionComponent->SetCollisionResponseToChannel(ECC_GameTraceChannel1, ECR_Overlap);
		}
		else
		{
			// ì¼ë°˜ ëª¨ë“œì—ì„œëŠ” ê¸°ì¡´ ì„¤ì •
			CollisionComponent->SetCollisionEnabled(ECollisionEnabled::QueryOnly);
			CollisionComponent->SetCollisionResponseToAllChannels(ECR_Ignore);
			CollisionComponent->SetCollisionResponseToChannel(ECC_Pawn, ECR_Overlap);
			CollisionComponent->SetCollisionResponseToChannel(ECC_GameTraceChannel1, ECR_Block);
		}
	}
	OnMouseCollisionReenabled.Broadcast();
}

void ASLMouseActor::UpdateOrbitMovement(float DeltaTime)
{
	if (!IsValid(TargetPlayer))
	{
		return;
	}

	OrbitCenter = TargetPlayer->GetActorLocation();
	
	OrbitAngle += OrbitSpeed * DeltaTime;
	if (OrbitAngle >= 360.0f)
	{
		OrbitAngle -= 360.0f;
	}

	FVector OrbitPosition = CalculateOrbitPosition();
	SetActorLocation(OrbitPosition);
}

void ASLMouseActor::UpdateDescentMovement(float DeltaTime)
{
	if (!IsValid(TargetPlayer))
	{
		return;
	}

	FVector PlayerLocation = TargetPlayer->GetActorLocation();
	FVector CurrentLocation = GetActorLocation();
	FVector DirectionToPlayer = (PlayerLocation - CurrentLocation).GetSafeNormal();
	
	if (DirectionToPlayer.IsZero())
	{
		return;
	}

	FVector MovementDelta = DirectionToPlayer * DescentSpeed * DeltaTime;
	FVector NewLocation = CurrentLocation + MovementDelta;
	SetActorLocation(NewLocation);
}

void ASLMouseActor::UpdateGrabMovement(float DeltaTime)
{
	FVector CurrentLocation = GetActorLocation();
	FVector DirectionToTarget = (GrabTargetLocation - CurrentLocation).GetSafeNormal();
	
	if (DirectionToTarget.IsZero())
	{
		return;
	}

	FVector MovementDelta = DirectionToTarget * GrabMoveSpeed * DeltaTime;
	FVector NewLocation = CurrentLocation + MovementDelta;
	SetActorLocation(NewLocation);

	float DistanceToTarget = FVector::Dist(CurrentLocation, GrabTargetLocation);
	if (DistanceToTarget <= 50.0f)
	{
		CompleteGrabPlayer();
	}
}

void ASLMouseActor::UpdateMeshRotation(float DeltaTime)
{
	if (!IsValid(MouseMeshComponent) || !IsValid(TargetPlayer))
	{
		return;
	}

	FVector MeshLocation = MouseMeshComponent->GetComponentLocation();
	FVector PlayerLocation = TargetPlayer->GetActorLocation();
    
	FRotator LookAtRotation = UKismetMathLibrary::FindLookAtRotation(MeshLocation, PlayerLocation);
    
	if (bIsInPhase3Mode)
	{
		LookAtRotation.Yaw -= 90.0f; 
		LookAtRotation.Pitch -= 20.0f; 
		LookAtRotation.Roll -= 10.0f; 
		
		
		FRotator CurrentRotation = MouseMeshComponent->GetComponentRotation();
		FRotator NewRotation = FMath::RInterpTo(CurrentRotation, LookAtRotation, DeltaTime, 5.0f);
		MouseMeshComponent->SetWorldRotation(NewRotation);
		
		
		FVector DirectionToPlayer = (PlayerLocation - GetActorLocation()).GetSafeNormal();
		FRotator ActorRotation = DirectionToPlayer.Rotation();
		FRotator CurrentActorRotation = GetActorRotation();
		FRotator NewActorRotation = FMath::RInterpTo(CurrentActorRotation, ActorRotation, DeltaTime, 3.0f);
		SetActorRotation(NewActorRotation);
	}
	else
	{
		// ê¸°ì¡´ ë¶€ë“œëŸ¬ìš´ íšŒì „
		LookAtRotation.Yaw -= 90.0f;
		LookAtRotation.Pitch -= 45.0f;
        
		FRotator CurrentRotation = MouseMeshComponent->GetComponentRotation();
		FRotator NewRotation = FMath::RInterpTo(CurrentRotation, LookAtRotation, DeltaTime, 3.0f);
		MouseMeshComponent->SetWorldRotation(NewRotation);
	}
}

void ASLMouseActor::UpdateMoveToOrbitMovement(float DeltaTime)
{
	if (!IsValid(TargetPlayer))
	{
		return;
	}

	OrbitCenter = TargetPlayer->GetActorLocation();
	MoveToOrbitTargetLocation = CalculateOrbitPosition();

	FVector CurrentLocation = GetActorLocation();
	FVector DirectionToTarget = (MoveToOrbitTargetLocation - CurrentLocation).GetSafeNormal();
	
	if (DirectionToTarget.IsZero())
	{
		SetMouseActorState(EMouseActorState::Orbiting);
		return;
	}

	FVector MovementDelta = DirectionToTarget * MoveToOrbitSpeed * DeltaTime;
	FVector NewLocation = CurrentLocation + MovementDelta;
	SetActorLocation(NewLocation);

	float DistanceToTarget = FVector::Dist(CurrentLocation, MoveToOrbitTargetLocation);
	if (DistanceToTarget <= 50.0f)
	{
		SetMouseActorState(EMouseActorState::Orbiting);
	}
}

void ASLMouseActor::StartGrabPlayer()
{
	if (!IsValid(TargetPlayer) || CurrentState != EMouseActorState::Descending || !CanGrabPlayer())
	{
		return;
	}

	SetMouseActorState(EMouseActorState::Grabbing);
	bCanGrab = false;

	FVector CurrentLocation = GetActorLocation();
	FVector DirectionFromPlayer = (CurrentLocation - TargetPlayer->GetActorLocation()).GetSafeNormal();
	GrabTargetLocation = CurrentLocation + (DirectionFromPlayer * GrabDistance);
	GrabTargetLocation.Z += GrabHeight;

	TargetPlayer->AttachToActor(this, FAttachmentTransformRules::KeepWorldTransform);
	TargetPlayer->CharacterDragged(true);
	
	if (UCharacterMovementComponent* MovementComp = TargetPlayer->GetCharacterMovement())
	{
		MovementComp->DisableMovement();
	}

	if (IsValid(GrabEffect) && IsValid(GetWorld()))
	{
		UNiagaraFunctionLibrary::SpawnSystemAtLocation(
			GetWorld(),
			GrabEffect,
			GetActorLocation(),
			GetActorRotation()
		);
	}

	if (IsValid(GrabSound) && IsValid(GetWorld()))
	{
		UGameplayStatics::PlaySoundAtLocation(
			GetWorld(),
			GrabSound,
			GetActorLocation()
		);
	}
}

void ASLMouseActor::CompleteGrabPlayer()
{
	if (CurrentState != EMouseActorState::Grabbing)
	{
		return;
	}

	if (IsValid(TargetPlayer))
	{
		// ì•ˆì „í•œ ë“œë¡­ ìœ„ì¹˜ ì°¾ê¸°
		FVector SafeDropLocation = FindSafeDropLocation(GetActorLocation());
        
		// í”Œë ˆì´ì–´ë¥¼ ì•ˆì „í•œ ìœ„ì¹˜ì— ë“œë¡­
		TargetPlayer->DetachFromActor(FDetachmentTransformRules::KeepWorldTransform);
		TargetPlayer->SetActorLocation(SafeDropLocation);
		TargetPlayer->CharacterDragged(false);
        
		if (UCharacterMovementComponent* MovementComp = TargetPlayer->GetCharacterMovement())
		{
			MovementComp->SetDefaultMovementMode();
		}
	}

	if (IsValid(CollisionComponent))
	{
		CollisionComponent->SetCollisionEnabled(ECollisionEnabled::NoCollision);
        
		FTimerHandle CollisionTimer;
		GetWorldTimerManager().SetTimer(
			CollisionTimer,
			this,
			&ASLMouseActor::OnCollisionReenabled,
			CollisionDisableTime,
			false
		);
	}

	ApplyGrabDamage();

	float RandomCooldown = GetRandomGrabCooldown();
	FTimerHandle CooldownTimer;
	GetWorldTimerManager().SetTimer(
		CooldownTimer,
		this,
		&ASLMouseActor::OnGrabCooldownFinished,
		RandomCooldown,
		false
	);
    
	SetMouseActorState(EMouseActorState::Orbiting);
    
	if (IsValid(TargetPlayer))
	{
		OrbitCenter = TargetPlayer->GetActorLocation();
		OrbitAngle = 0.0f;
        
		FVector OrbitPosition = CalculateOrbitPosition();
		SetActorLocation(OrbitPosition);
	}

	OnMouseGrabCompleted.Broadcast();
}

void ASLMouseActor::ApplyGrabDamage()
{
	if (!IsValid(TargetPlayer))
	{
		return;
	}

	if (UBattleComponent* PlayerBattleComp = TargetPlayer->FindComponentByClass<UBattleComponent>())
	{
		FHitResult HitResult;
		HitResult.ImpactPoint = TargetPlayer->GetActorLocation();
		HitResult.Location = TargetPlayer->GetActorLocation();
		HitResult.ImpactNormal = (GetActorLocation() - TargetPlayer->GetActorLocation()).GetSafeNormal();
		HitResult.Distance = FVector::Dist(GetActorLocation(), TargetPlayer->GetActorLocation());
		HitResult.TraceStart = GetActorLocation();
		HitResult.TraceEnd = TargetPlayer->GetActorLocation();
		
		PlayerBattleComp->ReceiveHitResult(GrabDamage, this, HitResult, EAttackAnimType::AAT_AISpecial);
	}
}

void ASLMouseActor::SetMouseActorState(EMouseActorState NewState)
{
	if (CurrentState != NewState)
	{
		CurrentState = NewState;
		OnMouseStateChanged.Broadcast(NewState);
	}
}

ASLPlayerCharacter* ASLMouseActor::FindPlayerCharacter()
{
	if (!IsValid(GetWorld()))
	{
		return nullptr;
	}

	APlayerController* PlayerController = GetWorld()->GetFirstPlayerController();
	if (!IsValid(PlayerController))
	{
		return nullptr;
	}

	APawn* PlayerPawn = PlayerController->GetPawn();
	if (!IsValid(PlayerPawn))
	{
		return nullptr;
	}

	return Cast<ASLPlayerCharacter>(PlayerPawn);
}

bool ASLMouseActor::IsPlayerInRange() const
{
	if (!IsValid(TargetPlayer))
	{
		return false;
	}

	float DistanceToPlayer = FVector::Dist(GetActorLocation(), TargetPlayer->GetActorLocation());
	return DistanceToPlayer <= DetectionRange;
}

bool ASLMouseActor::CanGrabPlayer() const
{
	if (bIsInPhase3Mode)
	{
		return false;
	}
    
	return bCanGrab && (CurrentState == EMouseActorState::Orbiting || CurrentState == EMouseActorState::Descending);
}

float ASLMouseActor::GetRandomGrabCooldown() const
{
   return FMath::FRandRange(GrabCooldownMin, GrabCooldownMax);
}

FVector ASLMouseActor::CalculateOrbitPosition() const
{
   float RadianAngle = FMath::DegreesToRadians(OrbitAngle);
   FVector OrbitPosition = OrbitCenter;
   OrbitPosition.X += FMath::Cos(RadianAngle) * OrbitRadius;
   OrbitPosition.Y += FMath::Sin(RadianAngle) * OrbitRadius;
   OrbitPosition.Z += OrbitHeight;
   
   return OrbitPosition;
}

void ASLMouseActor::StartPhase3HorrorMode()
{
	if (CurrentState == EMouseActorState::Destroyed)
	{
		return;
	}

	bIsInPhase3Mode = true;
	SetMouseActorState(EMouseActorState::Descending);
	
	// Phase3ì—ì„œëŠ” ì½œë¦¬ì „ì„ ë” ì‘ê²Œ ì„¤ì •í•˜ê³  ê²¹ì¹¨ë§Œ í—ˆìš©
	if (CollisionComponent)
	{
		CollisionComponent->SetSphereRadius(DetectionRange * 0.5f); // ì½œë¦¬ì „ ë²”ìœ„ ì¶•ì†Œ
		CollisionComponent->SetCollisionEnabled(ECollisionEnabled::QueryOnly);
		CollisionComponent->SetCollisionResponseToAllChannels(ECR_Ignore);
		CollisionComponent->SetCollisionResponseToChannel(ECC_Pawn, ECR_Overlap);
		CollisionComponent->SetCollisionResponseToChannel(ECC_GameTraceChannel1, ECR_Overlap);
	}
}

void ASLMouseActor::UpdatePhase3Movement(float DeltaTime)
{
	if (!IsValid(TargetPlayer))
	{
		return;
	}

	bIsPlayerLookingAtMe = IsPlayerLookingAtMe();
   
	if (bIsPlayerLookingAtMe)
	{
		return;
	}

	FVector PlayerLocation = TargetPlayer->GetActorLocation();
	FVector CurrentLocation = GetActorLocation();
	float DistanceToPlayer = FVector::Dist(CurrentLocation, PlayerLocation);
   
	// ìŠ¤ìœ• ê³µê²© ë²”ìœ„ ë‚´ì— ìˆê³  ì¿¨íƒ€ì„ì´ ëë‚¬ìœ¼ë©´ ê³µê²©
	if (DistanceToPlayer <= SweepAttackRange && bCanSweepAttack)
	{
		PerformSweepAttack();
		return;
	}
   
	if (DistanceToPlayer > Phase3StopDistance)
	{
		FVector DirectionToPlayer = (PlayerLocation - CurrentLocation).GetSafeNormal();
		FVector MovementDelta = DirectionToPlayer * Phase3ChaseSpeed * DeltaTime;
		FVector NewLocation = CurrentLocation + MovementDelta;
		SetActorLocation(NewLocation);
	}
}


bool ASLMouseActor::IsPlayerLookingAtMe() const
{
	if (!IsValid(TargetPlayer))
	{
		return false;
	}

	// í”Œë ˆì´ì–´ ì»¨íŠ¸ë¡¤ëŸ¬ì—ì„œ ì¹´ë©”ë¼ ì •ë³´ ê°€ì ¸ì˜¤ê¸°
	APlayerController* PlayerController = Cast<APlayerController>(TargetPlayer->GetController());
	if (!PlayerController)
	{
		return false;
	}

	// ì¹´ë©”ë¼ ìœ„ì¹˜ì™€ ë°©í–¥ ê°€ì ¸ì˜¤ê¸°
	FVector CameraLocation;
	FRotator CameraRotation;
	PlayerController->GetPlayerViewPoint(CameraLocation, CameraRotation);

	FVector CameraForward = CameraRotation.Vector();
	FVector MouseLocation = GetActorLocation();

	// ì¹´ë©”ë¼ì—ì„œ ë§ˆìš°ìŠ¤ ì•¡í„°ë¡œì˜ ë°©í–¥
	FVector DirectionToMouse = (MouseLocation - CameraLocation).GetSafeNormal();

	// ê°ë„ í™•ì¸
	float DotProduct = FVector::DotProduct(CameraForward, DirectionToMouse);
	DotProduct = FMath::Clamp(DotProduct, -1.0f, 1.0f);
	float AngleInDegrees = FMath::RadiansToDegrees(FMath::Acos(DotProduct));

	// ì‹œì•¼ê° ë²”ìœ„ ë°–ì´ë©´ false
	if (AngleInDegrees > PlayerLookCheckAngle)
	{
		return false;
	}

	// ë ˆì´ìºìŠ¤íŠ¸ë¡œ ì‹¤ì œë¡œ ë³´ì´ëŠ”ì§€ í™•ì¸
	FHitResult HitResult;
	FCollisionQueryParams QueryParams;
	QueryParams.AddIgnoredActor(this);
	QueryParams.AddIgnoredActor(TargetPlayer);
	QueryParams.bTraceComplex = false;

	// ì¹´ë©”ë¼ì—ì„œ ë§ˆìš°ìŠ¤ ì•¡í„°ë¡œ ë ˆì´ìºìŠ¤íŠ¸
	bool bHit = GetWorld()->LineTraceSingleByChannel(
		HitResult,
		CameraLocation,
		MouseLocation,
		ECC_Visibility,
		QueryParams
	);

	return !bHit;
}

void ASLMouseActor::RestoreOriginalAppearance()
{
   if (!IsValid(MouseMeshComponent))
   {
       return;
   }

   if (IsValid(OriginalMesh))
   {
       MouseMeshComponent->SetStaticMesh(OriginalMesh);
   }
	
	MouseMeshComponent->SetWorldScale3D(FVector(1.0f, 1.0f, 1.0f));
}

void ASLMouseActor::PerformSweepAttack()
{
	if (!bCanSweepAttack || !bIsInPhase3Mode || !IsValid(TargetPlayer))
	{
		return;
	}
    
	bCanSweepAttack = false;
	CurrentHitCount = 0;
	MultiHitTargets.Empty();
    
	// ë‚˜ì´ì•„ê°€ë¼ ì´í™íŠ¸ ì¬ìƒ (í”Œë ˆì´ì–´ ë°©í–¥ìœ¼ë¡œ)
	if (IsValid(SweepAttackEffect) && IsValid(GetWorld()))
	{
		FVector StartLocation = GetActorLocation();
		FVector PlayerLocation = TargetPlayer->GetActorLocation();
		
		// í”Œë ˆì´ì–´ ë°©í–¥ ê³„ì‚° (ìˆ˜í‰ë©´ì—ì„œ)
		FVector DirectionToPlayer = (PlayerLocation - StartLocation);
		DirectionToPlayer.Z = 0.0f; // ìˆ˜í‰ ë°©í–¥ë§Œ ê³ ë ¤
		DirectionToPlayer.Normalize();
		
		// ì´í™íŠ¸ íšŒì „ ê³„ì‚° (Up Vectorê°€ í”Œë ˆì´ì–´ë¥¼ í–¥í•˜ë„ë¡)
		FRotator EffectRotation = UKismetMathLibrary::MakeRotFromZ(DirectionToPlayer);
		
		UNiagaraFunctionLibrary::SpawnSystemAtLocation(
			GetWorld(),
			SweepAttackEffect,
			StartLocation,
			EffectRotation
		);
		
		UE_LOG(LogTemp, Warning, TEXT("Mouse Actor: Effect spawned at rotation Yaw=%f, Player direction=%s"), 
			EffectRotation.Yaw, *DirectionToPlayer.ToString());
	}
    
	// ì²« ë²ˆì§¸ íˆíŠ¸ ì‹¤í–‰
	ExecuteSweepAttack();
	CurrentHitCount++;
    
	// ë‹¤ë‹¨ íˆíŠ¸ íƒ€ì´ë¨¸ ì‹œì‘
	if (SweepAttackHitCount > 1)
	{
		StartMultiHitTimer();
	}
    
	// ì¿¨íƒ€ì„ ì‹œì‘
	if (IsValid(GetWorld()))
	{
		GetWorld()->GetTimerManager().SetTimer(
			SweepAttackCooldownTimer,
			this,
			&ASLMouseActor::OnSweepAttackCooldownFinished,
			SweepAttackCooldown,
			false
		);
	}
}

void ASLMouseActor::ExecuteSweepAttack()
{
    if (!IsValid(GetWorld()) || !IsValid(TargetPlayer))
    {
        return;
    }
    
    FVector StartLocation = GetActorLocation();
    
    // í”Œë ˆì´ì–´ ë°©í–¥ìœ¼ë¡œ ìŠ¤ìœ• ê³µê²©
    FVector DirectionToPlayer = (TargetPlayer->GetActorLocation() - StartLocation).GetSafeNormal();
    FVector EndLocation = StartLocation + (DirectionToPlayer * SweepAttackRange);

    if (bShowSweepDebug)
    {
        // ë””ë²„ê·¸ ë°•ìŠ¤ë¥¼ í”Œë ˆì´ì–´ ë°©í–¥ìœ¼ë¡œ í‘œì‹œ
        FVector CenterPoint = (StartLocation + EndLocation) * 0.5f;
        FRotator BoxRotation = DirectionToPlayer.Rotation();
        
        FColor DebugColor = (CurrentHitCount == 1) ? FColor::Red : FColor::Orange;
        
        DrawDebugBox(
            GetWorld(),
            CenterPoint,
            FVector(SweepAttackRange * 0.5f, 50.0f, 50.0f),
            BoxRotation.Quaternion(),
            DebugColor,
            false,
            SweepAttackHitInterval + 0.5f
        );
    }
    
    // ìŠ¤ìœ• íŒŒë¼ë¯¸í„° ì„¤ì •
    FCollisionShape SweepShape = FCollisionShape::MakeBox(FVector(50.0f, 50.0f, 50.0f));
    
    FCollisionQueryParams QueryParams;
    QueryParams.AddIgnoredActor(this);
    
    TArray<FHitResult> HitResults;
    
    // í”Œë ˆì´ì–´ ë°©í–¥ìœ¼ë¡œ ìŠ¤ìœ• ì‹¤í–‰
    FQuat SweepRotation = DirectionToPlayer.Rotation().Quaternion();
    
    bool bHit = GetWorld()->SweepMultiByChannel(
        HitResults,
        StartLocation,
        EndLocation,
        SweepRotation,
        ECC_Pawn,
        SweepShape,
        QueryParams
    );
    
    if (bHit)
    {
        for (const FHitResult& Hit : HitResults)
        {
            if (AActor* HitActor = Hit.GetActor())
            {
                // ì²« ë²ˆì§¸ íˆíŠ¸ì´ê±°ë‚˜ ë‹¤ë‹¨ íˆíŠ¸ì—ì„œ ì´ë¯¸ ë§ì€ ëŒ€ìƒì¸ ê²½ìš° ì²˜ë¦¬
                if (CurrentHitCount == 1 || MultiHitTargets.Contains(HitActor))
                {
                    // ì²« ë²ˆì§¸ íˆíŠ¸ì¼ ë•Œ ë‹¤ë‹¨ íˆíŠ¸ ëŒ€ìƒì— ì¶”ê°€
                    if (CurrentHitCount == 1)
                    {
                        MultiHitTargets.Add(HitActor);
                    }
                    
                    // ë°°í‹€ ì»´í¬ë„ŒíŠ¸ë¥¼ í†µí•´ ë°ë¯¸ì§€ ì ìš©
                    if (UBattleComponent* TargetBattleComp = HitActor->FindComponentByClass<UBattleComponent>())
                    {
                        float CurrentDamage = SweepAttackDamage;
                        
                        // ë‹¤ë‹¨ íˆíŠ¸ì¼ ê²½ìš° ë°ë¯¸ì§€ ì¡°ì • (ì„ íƒì‚¬í•­)
                        if (CurrentHitCount > 1)
                        {
                            CurrentDamage *= 0.7f; // í›„ì† íˆíŠ¸ëŠ” 70% ë°ë¯¸ì§€
                        }
                        
                        TargetBattleComp->ReceiveHitResult(
                            CurrentDamage,
                            this,
                            Hit,
                            EAttackAnimType::AAT_AIProjectile
                        );
                        
                        UE_LOG(LogTemp, Warning, TEXT("Mouse Actor Phase3: Sweep attack hit %s (Hit %d/%d)"), 
                            *HitActor->GetName(), CurrentHitCount, SweepAttackHitCount);
                    }
                }
            }
        }
    }
}

void ASLMouseActor::OnSweepAttackCooldownFinished()
{
    bCanSweepAttack = true;
}

void ASLMouseActor::StartMultiHitTimer()
{
	if (IsValid(GetWorld()) && CurrentHitCount < SweepAttackHitCount)
	{
		GetWorld()->GetTimerManager().SetTimer(
			MultiHitTimer,
			this,
			&ASLMouseActor::OnMultiHitTimerFinished,
			SweepAttackHitInterval,
			false
		);
	}
}

void ASLMouseActor::OnMultiHitTimerFinished()
{
	if (CurrentHitCount < SweepAttackHitCount)
	{
		CurrentHitCount++;
		ExecuteSweepAttack();
        
		// ë‹¤ìŒ íˆíŠ¸ê°€ ìˆìœ¼ë©´ íƒ€ì´ë¨¸ ì¬ì‹œì‘
		if (CurrentHitCount < SweepAttackHitCount)
		{
			StartMultiHitTimer();
		}
		else
		{
			// ëª¨ë“  íˆíŠ¸ ì™„ë£Œ
			UE_LOG(LogTemp, Warning, TEXT("Mouse Actor: Multi-hit sweep attack completed (%d hits)"), SweepAttackHitCount);
		}
	}
}

void ASLMouseActor::ApplyWallStun(float StunDuration)
{
    // í”Œë ˆì´ì–´ë¥¼ ê·¸ë© ì¤‘ì´ë©´ ìŠ¤í„´ ì ìš©í•˜ì§€ ì•ŠìŒ
    if (IsGrabbingPlayer())
    {
        UE_LOG(LogTemp, Warning, TEXT("âŒ Cannot apply stun - Mouse Actor is grabbing player"));
        return;
    }

    if (bIsStunned || CurrentState == EMouseActorState::Destroyed)
    {
        UE_LOG(LogTemp, Warning, TEXT("âŒ Cannot apply stun - Already stunned or destroyed"));
        return;
    }

    float ActualStunDuration = (StunDuration > 0) ? StunDuration : DefaultWallStunDuration;
    
    bIsStunned = true;
    bIsAttackable = true;
    
    // BattleComponent í™œì„±í™”
    if (UBattleComponent* MouseBattleComp = FindComponentByClass<UBattleComponent>())
    {
        MouseBattleComp->SetComponentTickEnabled(true);
    }
    else
    {
        UE_LOG(LogTemp, Error, TEXT("âŒ BattleComponent not found during stun!"));
    }
    
    // ë©”ì‹œ ì»´í¬ë„ŒíŠ¸ ê°•ì œ í™œì„±í™”
    if (MouseMeshComponent)
    {
        MouseMeshComponent->SetCollisionEnabled(ECollisionEnabled::QueryAndPhysics);
        MouseMeshComponent->SetCollisionResponseToChannel(ECC_GameTraceChannel1, ECR_Block);
    }
    
    // ì½œë¦¬ì „ ì»´í¬ë„ŒíŠ¸ ê°•ì œ í™œì„±í™”
    if (CollisionComponent)
    {
        CollisionComponent->SetCollisionEnabled(ECollisionEnabled::QueryAndPhysics);
        CollisionComponent->SetCollisionResponseToChannel(ECC_GameTraceChannel1, ECR_Block);
    }
    
    // ìŠ¤í„´ ì´í™íŠ¸ ì¬ìƒ
    if (IsValid(StunEffect) && IsValid(GetWorld()))
    {
        UNiagaraFunctionLibrary::SpawnSystemAtLocation(
            GetWorld(),
            StunEffect,
            GetActorLocation(),
            GetActorRotation()
        );
    }
    
    // ìŠ¤í„´ ì‚¬ìš´ë“œ ì¬ìƒ
    if (IsValid(StunSound) && IsValid(GetWorld()))
    {
        UGameplayStatics::PlaySoundAtLocation(
            GetWorld(),
            StunSound,
            GetActorLocation()
        );
    }
    
    // ìŠ¤í„´ íšŒë³µ íƒ€ì´ë¨¸ ì„¤ì •
    if (IsValid(GetWorld()))
    {
        GetWorld()->GetTimerManager().SetTimer(
            StunRecoveryTimer,
            this,
            &ASLMouseActor::OnStunRecovery,
            ActualStunDuration,
            false
        );
    }
    
    // ì´ë²¤íŠ¸ ë¸Œë¡œë“œìºìŠ¤íŠ¸
    OnMouseActorStunned.Broadcast();
}

bool ASLMouseActor::IsStunned() const
{
    return bIsStunned;
}

void ASLMouseActor::EnableAttackability()
{
	bIsAttackable = true;
    
	UE_LOG(LogTemp, Warning, TEXT("ğŸ”“ EnableAttackability called"));
    
	// BattleComponent í™œì„±í™”
	if (UBattleComponent* MouseBattleComp = FindComponentByClass<UBattleComponent>())
	{
		MouseBattleComp->SetComponentTickEnabled(true);
		UE_LOG(LogTemp, Warning, TEXT("   âœ… BattleComponent enabled"));
	}
	else
	{
		UE_LOG(LogTemp, Error, TEXT("   âŒ BattleComponent not found!"));
	}
    
	// ë©”ì‹œ ì»´í¬ë„ŒíŠ¸ ì½œë¦¬ì „ ì„¤ì •
	if (MouseMeshComponent)
	{
		MouseMeshComponent->SetCollisionEnabled(ECollisionEnabled::QueryAndPhysics);
		MouseMeshComponent->SetCollisionResponseToChannel(ECC_GameTraceChannel1, ECR_Block);
		UE_LOG(LogTemp, Warning, TEXT("   âœ… MouseMeshComponent collision enabled"));
	}
    
	// ì½œë¦¬ì „ ì»´í¬ë„ŒíŠ¸ ì„¤ì •
	if (CollisionComponent)
	{
		CollisionComponent->SetCollisionEnabled(ECollisionEnabled::QueryAndPhysics);
		CollisionComponent->SetCollisionResponseToChannel(ECC_GameTraceChannel1, ECR_Block);
		UE_LOG(LogTemp, Warning, TEXT("   âœ… CollisionComponent collision enabled"));
	}
    
	UE_LOG(LogTemp, Display, TEXT("âœ… Mouse Actor attackability enabled - bIsAttackable: %s"), bIsAttackable ? TEXT("YES") : TEXT("NO"));
}

void ASLMouseActor::DisableAttackability()
{
	bIsAttackable = false;
    
	UE_LOG(LogTemp, Warning, TEXT("ğŸ”’ DisableAttackability called"));
    
	// BattleComponent ë¹„í™œì„±í™”
	if (UBattleComponent* MouseBattleComp = FindComponentByClass<UBattleComponent>())
	{
		MouseBattleComp->SetComponentTickEnabled(false);
		UE_LOG(LogTemp, Warning, TEXT("   âœ… BattleComponent disabled"));
	}
    
	// ë©”ì‹œ ì»´í¬ë„ŒíŠ¸ ì½œë¦¬ì „ì„ ê²¹ì¹¨ë§Œ í—ˆìš©
	if (MouseMeshComponent)
	{
		MouseMeshComponent->SetCollisionResponseToChannel(ECC_GameTraceChannel1, ECR_Ignore);
		UE_LOG(LogTemp, Warning, TEXT("   âœ… MouseMeshComponent attack collision disabled"));
	}
    
	// ì½œë¦¬ì „ ì»´í¬ë„ŒíŠ¸ë¥¼ ê²¹ì¹¨ë§Œ í—ˆìš©
	if (CollisionComponent)
	{
		CollisionComponent->SetCollisionResponseToChannel(ECC_GameTraceChannel1, ECR_Ignore);
		UE_LOG(LogTemp, Warning, TEXT("   âœ… CollisionComponent attack collision disabled"));
	}
    
	UE_LOG(LogTemp, Display, TEXT("âœ… Mouse Actor attackability disabled - bIsAttackable: %s"), bIsAttackable ? TEXT("YES") : TEXT("NO"));
}

void ASLMouseActor::OnStunRecovery()
{
    UE_LOG(LogTemp, Warning, TEXT("ğŸ”„ Mouse Actor recovering from stun"));
    
    bIsStunned = false;
    bIsAttackable = false; // ìŠ¤í„´ íšŒë³µ í›„ ë‹¤ì‹œ ê³µê²© ë¶ˆê°€ëŠ¥
    
    // BattleComponent ë¹„í™œì„±í™”
    if (UBattleComponent* MouseBattleComp = FindComponentByClass<UBattleComponent>())
    {
        MouseBattleComp->SetComponentTickEnabled(false);
    }
    
    // ì½œë¦¬ì „ì„ ì›ë˜ëŒ€ë¡œ ë³µêµ¬
    if (CollisionComponent)
    {
        CollisionComponent->SetCollisionEnabled(ECollisionEnabled::QueryOnly);
        CollisionComponent->SetCollisionResponseToChannel(ECC_GameTraceChannel1, ECR_Ignore);
    }
    
    // ì´ë²¤íŠ¸ ë¸Œë¡œë“œìºìŠ¤íŠ¸
    OnMouseActorStunRecovered.Broadcast();
    
    UE_LOG(LogTemp, Display, TEXT("âœ… Mouse Actor stun recovery completed"));
}

void ASLMouseActor::DebugAttackability()
{
	UE_LOG(LogTemp, Warning, TEXT("=== MOUSE ACTOR DEBUG INFO ==="));
	UE_LOG(LogTemp, Warning, TEXT("bIsAttackable: %s"), bIsAttackable ? TEXT("YES") : TEXT("NO"));
	UE_LOG(LogTemp, Warning, TEXT("bIsStunned: %s"), bIsStunned ? TEXT("YES") : TEXT("NO"));
	UE_LOG(LogTemp, Warning, TEXT("CurrentState: %d"), static_cast<int32>(CurrentState));
	UE_LOG(LogTemp, Warning, TEXT("CurrentHealth: %f / %f"), CurrentHealth, MaxHealth);
    
	if (UBattleComponent* BattleComp = FindComponentByClass<UBattleComponent>())
	{
		UE_LOG(LogTemp, Warning, TEXT("BattleComponent Tick Enabled: %s"), BattleComp->IsComponentTickEnabled() ? TEXT("YES") : TEXT("NO"));
	}
	else
	{
		UE_LOG(LogTemp, Error, TEXT("âŒ BattleComponent NOT FOUND!"));
	}
    
	if (MouseMeshComponent)
	{
		UE_LOG(LogTemp, Warning, TEXT("MouseMesh Collision Enabled: %s"), 
			   MouseMeshComponent->GetCollisionEnabled() != ECollisionEnabled::NoCollision ? TEXT("YES") : TEXT("NO"));
		UE_LOG(LogTemp, Warning, TEXT("MouseMesh GameTraceChannel1 Response: %d"), 
			   static_cast<int32>(MouseMeshComponent->GetCollisionResponseToChannel(ECC_GameTraceChannel1)));
	}
    
	if (CollisionComponent)
	{
		UE_LOG(LogTemp, Warning, TEXT("CollisionComponent Collision Enabled: %s"), 
			   CollisionComponent->GetCollisionEnabled() != ECollisionEnabled::NoCollision ? TEXT("YES") : TEXT("NO"));
		UE_LOG(LogTemp, Warning, TEXT("CollisionComponent GameTraceChannel1 Response: %d"), 
			   static_cast<int32>(CollisionComponent->GetCollisionResponseToChannel(ECC_GameTraceChannel1)));
	}
	UE_LOG(LogTemp, Warning, TEXT("=============================="));
}

bool ASLMouseActor::IsGrabbingPlayer() const
{
	return CurrentState == EMouseActorState::Grabbing;
}

FVector ASLMouseActor::FindSafeDropLocation(const FVector& CurrentLocation) const
{
    if (!IsValid(GetWorld()))
    {
        return CurrentLocation;
    }

    // 1. í˜„ì¬ ìœ„ì¹˜ì—ì„œ ì•„ë˜ë¡œ ë ˆì´ìºìŠ¤íŠ¸
    FVector StartLocation = CurrentLocation;
    FVector EndLocation = StartLocation - FVector(0, 0, 2000.0f); // 2000 ìœ ë‹› ì•„ë˜ë¡œ

    FHitResult HitResult;
    FCollisionQueryParams QueryParams;
    QueryParams.bTraceComplex = false;
    QueryParams.AddIgnoredActor(this);
    if (IsValid(TargetPlayer))
    {
        QueryParams.AddIgnoredActor(TargetPlayer);
    }

    bool bHit = GetWorld()->LineTraceSingleByChannel(
        HitResult,
        StartLocation,
        EndLocation,
        ECC_WorldStatic,
        QueryParams
    );

    if (bHit && IsLocationSafe(HitResult.Location))
    {
        // ë•…ì—ì„œ ì•½ê°„ ìœ„ì— í”Œë ˆì´ì–´ë¥¼ ë“œë¡­
        return HitResult.Location + FVector(0, 0, 100.0f);
    }

    // 2. ì£¼ë³€ ì—¬ëŸ¬ ë°©í–¥ìœ¼ë¡œ ê²€ìƒ‰
    TArray<FVector> SearchDirections = {
        FVector(200, 0, 0),      // ì•
        FVector(-200, 0, 0),     // ë’¤
        FVector(0, 200, 0),      // ìš°
        FVector(0, -200, 0),     // ì¢Œ
        FVector(200, 200, 0),    // ì•ìš°
        FVector(-200, 200, 0),   // ë’¤ìš°
        FVector(200, -200, 0),   // ì•ì¢Œ
        FVector(-200, -200, 0)   // ë’¤ì¢Œ
    };

    for (const FVector& Direction : SearchDirections)
    {
        FVector SearchStart = CurrentLocation + Direction;
        FVector SearchEnd = SearchStart - FVector(0, 0, 2000.0f);

        if (GetWorld()->LineTraceSingleByChannel(
            HitResult,
            SearchStart,
            SearchEnd,
            ECC_WorldStatic,
            QueryParams))
        {
            if (IsLocationSafe(HitResult.Location))
            {
                return HitResult.Location + FVector(0, 0, 100.0f);
            }
        }
    }

    // 3. ì•ˆì „í•œ ìœ„ì¹˜ë¥¼ ì°¾ì§€ ëª»í–ˆìœ¼ë©´ ì›ë˜ í”Œë ˆì´ì–´ ìœ„ì¹˜ ë°˜í™˜
    if (IsValid(TargetPlayer))
    {
        return TargetPlayer->GetActorLocation();
    }

    return CurrentLocation;
}

bool ASLMouseActor::IsLocationSafe(const FVector& Location) const
{
    if (!IsValid(GetWorld()))
    {
        return false;
    }

    // í•´ë‹¹ ìœ„ì¹˜ì— ì¶©ë¶„í•œ ê³µê°„ì´ ìˆëŠ”ì§€ í™•ì¸
    FVector CheckStart = Location + FVector(0, 0, 50.0f);
    FVector CheckEnd = Location + FVector(0, 0, 200.0f); // í”Œë ˆì´ì–´ ë†’ì´ë§Œí¼

    FCollisionQueryParams QueryParams;
    QueryParams.bTraceComplex = false;
    QueryParams.AddIgnoredActor(this);
    if (IsValid(TargetPlayer))
    {
        QueryParams.AddIgnoredActor(TargetPlayer);
    }

    // ìœ„ìª½ì— ì¥ì• ë¬¼ì´ ì—†ëŠ”ì§€ í™•ì¸
    bool bBlocked = GetWorld()->LineTraceTestByChannel(
        CheckStart,
        CheckEnd,
        ECC_WorldStatic,
        QueryParams
    );

    return !bBlocked;
}