#include "SLPhase4FallingFloor.h"

#include "Components/StaticMeshComponent.h"
#include "Engine/Engine.h"
#include "TimerManager.h"

#if WITH_EDITOR
#include "Editor.h"
#endif

ASLPhase4FallingFloor::ASLPhase4FallingFloor()
{
    PrimaryActorTick.bCanEverTick = false;

    CollapseDelay = 1.0f;
    
    DefaultSafePatterns.Add(TEXT("Stay"));
}

void ASLPhase4FallingFloor::BeginPlay()
{
    Super::BeginPlay();
    
    if (IsValid(GetWorld()))
    {
        FTimerHandle InitTimer;
        GetWorld()->GetTimerManager().SetTimer(
            InitTimer,
            [this]()
            {
                CollectAllMeshComponents();
                
                SetMeshesToSafeByName(DefaultSafePatterns);
            },
            0.1f,  // 0.1Ï¥à ÎîúÎ†àÏù¥
            false
        );
    }
}

void ASLPhase4FallingFloor::OnConstruction(const FTransform& Transform)
{
    Super::OnConstruction(Transform);
    
    CollectAllMeshComponents();
}

void ASLPhase4FallingFloor::StartFloorCollapse()
{
    OnFloorCollapseStarted.Broadcast();
    
    if (IsValid(GetWorld()))
    {
        GetWorld()->GetTimerManager().SetTimer(
            CollapseTimer,
            this,
            &ASLPhase4FallingFloor::OnCollapseDelayFinished,
            CollapseDelay,
            false
        );
    }
}

void ASLPhase4FallingFloor::ResetFloor()
{
    if (IsValid(GetWorld()))
    {
        GetWorld()->GetTimerManager().ClearTimer(CollapseTimer);
    }

    // Î™®Îì† Î©îÏãú Î¨ºÎ¶¨ ÎπÑÌôúÏÑ±Ìôî Î∞è ÏõêÎûò ÏúÑÏπòÎ°ú Î≥µÍµ¨
    for (UStaticMeshComponent* MeshComp : AllMeshComponents)
    {
        if (IsValid(MeshComp))
        {
            MeshComp->SetSimulatePhysics(false);
            MeshComp->SetCollisionObjectType(ECC_WorldStatic);
            
            // Î∂ÄÎ™®Ïóê Îã§Ïãú Ïñ¥ÌÉúÏπò (Î∂ÑÎ¶¨ÎêòÏóàÎçò Í≤ΩÏö∞)
            if (!MeshComp->IsAttachedTo(RootComponent))
            {
                MeshComp->AttachToComponent(
                    RootComponent,
                    FAttachmentTransformRules::KeepRelativeTransform
                );
            }
        }
    }
}

void ASLPhase4FallingFloor::RefreshMeshList()
{
    CollectAllMeshComponents();
    
    // Î™©Î°ù Ï∂úÎ†•
    for (int32 i = 0; i < AllMeshComponents.Num(); i++)
    {
        if (IsValid(AllMeshComponents[i]))
        {
            UE_LOG(LogTemp, Display, TEXT("üì¶ [%d] %s"), i, *AllMeshComponents[i]->GetName());
        }
    }
}

void ASLPhase4FallingFloor::SetAllMeshesToFall()
{
    SafeMeshComponents.Empty();
}

void ASLPhase4FallingFloor::SetAllMeshesToSafe()
{
    SafeMeshComponents = AllMeshComponents;
}

void ASLPhase4FallingFloor::TestStayPattern()
{
    
    TArray<FString> TestPatterns;
    TestPatterns.Add(TEXT("Stay"));
    
    SetMeshesToSafeByName(TestPatterns);
}

void ASLPhase4FallingFloor::ApplyDefaultPatterns()
{
    SetMeshesToSafeByName(DefaultSafePatterns);
}

void ASLPhase4FallingFloor::SetMeshesToSafeByName(const TArray<FString>& SafePatterns)
{
    SafeMeshComponents.Empty();
    
    for (UStaticMeshComponent* MeshComp : AllMeshComponents)
    {
        if (!IsValid(MeshComp))
        {
            continue;
        }
        
        FString MeshName = MeshComp->GetName();
        
        bool bIsSafe = false;
        
        // Ìå®ÌÑ¥ ÌôïÏù∏
        for (const FString& Pattern : SafePatterns)
        {
            
            if (MeshName.Contains(Pattern))
            {
                bIsSafe = true;
                SafeMeshComponents.Add(MeshComp);
                break;
            }
        }
    }
}

void ASLPhase4FallingFloor::SetMeshesToFallByName(const TArray<FString>& FallPatterns)
{
    
    for (const FString& Pattern : FallPatterns)
    {
        for (int32 i = SafeMeshComponents.Num() - 1; i >= 0; i--)
        {
            if (IsValid(SafeMeshComponents[i]) && SafeMeshComponents[i]->GetName().Contains(Pattern))
            {
                SafeMeshComponents.RemoveAt(i);
            }
        }
    }
}

void ASLPhase4FallingFloor::CollectAllMeshComponents()
{
    AllMeshComponents.Empty();
    
    // Ïù¥ Ïï°ÌÑ∞Ïùò Î™®Îì† StaticMeshComponent ÏàòÏßë (ÌïòÏúÑ Ïª¥Ìè¨ÎÑåÌä∏ Ìè¨Ìï®)
    TArray<UStaticMeshComponent*> FoundMeshes;
    GetComponents<UStaticMeshComponent>(FoundMeshes, true); // true = ÌïòÏúÑ Ïª¥Ìè¨ÎÑåÌä∏ Ìè¨Ìï®
    
    for (UStaticMeshComponent* MeshComp : FoundMeshes)
    {
        if (IsValid(MeshComp) && MeshComp->GetStaticMesh())
        {
            AllMeshComponents.Add(MeshComp);
        }
    }
}

void ASLPhase4FallingFloor::MakeMeshFall(UStaticMeshComponent* MeshComp)
{
    if (!IsValid(MeshComp))
    {
        return;
    }

    // Î∂ÄÎ™®ÏóêÏÑú Î∂ÑÎ¶¨
    MeshComp->DetachFromComponent(FDetachmentTransformRules::KeepWorldTransform);
    
    // Î¨ºÎ¶¨ ÏÑ§Ï†ï
    MeshComp->SetCollisionEnabled(ECollisionEnabled::QueryAndPhysics);
    MeshComp->SetCollisionObjectType(ECC_WorldDynamic);
    MeshComp->SetCollisionResponseToAllChannels(ECR_Block);
    MeshComp->SetCollisionResponseToChannel(ECC_Camera, ECR_Ignore);
    
    // Î¨ºÎ¶¨ ÌôúÏÑ±Ìôî
    MeshComp->SetSimulatePhysics(true);
}

bool ASLPhase4FallingFloor::IsSafeMesh(UStaticMeshComponent* MeshComp) const
{
    return SafeMeshComponents.Contains(MeshComp);
}

void ASLPhase4FallingFloor::OnCollapseDelayFinished()
{
    for (UStaticMeshComponent* MeshComp : AllMeshComponents)
    {
        if (IsValid(MeshComp))
        {
            if (!IsSafeMesh(MeshComp))
            {
                MakeMeshFall(MeshComp);
            }
        }
    }
    
    OnFloorCollapseCompleted.Broadcast();
}